//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeatherForecast
    {
        public int ForecastId { get; set; }
        public double AtmosphericPressure { get; set; }
        public double AirTemperature { get; set; }
        public double PressureTendency { get; set; }
        public double RelativeHumidity { get; set; }
        public double Pressure { get; set; }
        public double CloudCover { get; set; }
        public System.DateTime LocalTime { get; set; }
        public double DewPointTemperature { get; set; }
        public double MeanWindSpeed { get; set; }
        public double Month { get; set; }
        public double Day { get; set; }
        public double Hour { get; set; }
        public double TypeOfDay { get; set; }

        public WeatherForecast()
        {

        }

        public WeatherForecast(double atmosphericPressure, double airTemperature, double pressureTendency, double relativeHumidity, double pressure, double cloudCover, DateTime localTime, double dewPointTemperature, double meanWindSpeed, double month, double day, double hour, double typeOfDay)
        {
            AtmosphericPressure = atmosphericPressure;
            AirTemperature = airTemperature;
            PressureTendency = pressureTendency;
            RelativeHumidity = relativeHumidity;
            Pressure = pressure;
            CloudCover = cloudCover;
            LocalTime = localTime;
            DewPointTemperature = dewPointTemperature;
            MeanWindSpeed = meanWindSpeed;
            Month = month;
            Day = day;
            Hour = hour;
            TypeOfDay = typeOfDay;
        }

        public WeatherForecast(double atmosphericPressure, double airTemperature, double pressureTendency, double relativeHumidity, double pressure, double cloudCover, DateTime localTime, double meanWindSpeed, double month, double day, double hour, double typeOfDay)
        {
            AtmosphericPressure = atmosphericPressure;
            AirTemperature = airTemperature;
            PressureTendency = pressureTendency;
            RelativeHumidity = relativeHumidity;
            Pressure = pressure;
            CloudCover = cloudCover;
            LocalTime = localTime;
            MeanWindSpeed = meanWindSpeed;
            Month = month;
            Day = day;
            Hour = hour;
            TypeOfDay = typeOfDay;
        }
    }
}
